switch to gotestsum

diff --git a/.github/workflows/mmctl-test-template.yml b/.github/workflows/mmctl-test-template.yml
--- a/.github/workflows/mmctl-test-template.yml
+++ b/.github/workflows/mmctl-test-template.yml
@@ -2,16 +2,23 @@ name: mmctl CI
 on:
   workflow_call:
     inputs:
+      name:
+        required: true
+        type: string
       datasource:
         required: true
         type: string
       drivername:
         required: true
         type: string
+      logsartifact:
+        required: true
+        type: string
 env:
   go-version: "1.19.5"
 jobs:
-  run-mmctl-tests:
+  test:
+    name: ${{ inputs.name }}
     runs-on: ubuntu-latest-8-cores
     env:
       COMPOSE_PROJECT_NAME: ghactions
@@ -30,21 +37,33 @@ jobs:
           cat ../tests/test-data.ldif | docker-compose --no-ansi exec -T openldap bash -c 'ldapadd -x -D "cn=admin,dc=mm,dc=test,dc=com" -w mostest';
           docker-compose --no-ansi exec -T minio sh -c 'mkdir -p /data/mattermost-test';
           docker-compose --no-ansi ps
-          cd ..
-      - name: Wait for docker compose
-        run: |
-          until docker network inspect ghactions_mm-test; do echo "Waiting for Docker Compose Network..."; sleep 1; done;
-          docker run --net ghactions_mm-test appropriate/curl:latest sh -c "until curl --max-time 5 --output - http://mysql:3306; do echo waiting for mysql; sleep 5; done;"
-          docker run --net ghactions_mm-test appropriate/curl:latest sh -c "until curl --max-time 5 --output - http://elasticsearch:9200; do echo waiting for elasticsearch; sleep 5; done;"
       - name: Run mmctl Tests
         run: |
-          mkdir -p client/plugins
-          cd server/build
           docker run --net ghactions_mm-test \
             --ulimit nofile=8096:8096 \
-            --env-file=dotenv/test.env \
+            --env-file=server/build/dotenv/test.env \
             --env MM_SQLSETTINGS_DATASOURCE="${{ inputs.datasource }}" \
-            -v ~/work/mattermost:/mattermost \
-            -w /mattermost/mattermost/server \
+            -v $(go env GOCACHE):/go/cache \
+            -e GOCACHE=/go/cache \
+            -v $PWD:/mattermost \
+            -w /mattermost/server \
             $BUILD_IMAGE \
-            make test-mmctl-coverage BUILD_NUMBER=$GITHUB_HEAD_REF-$GITHUB_RUN_ID MM_SERVER_PATH=/mattermost/mattermost/server
+            make test-mmctl-coverage BUILD_NUMBER=$GITHUB_HEAD_REF-$GITHUB_RUN_ID
+      - name: Stop docker compose
+        run: |
+          docker-compose --no-ansi stop
+      - name: Archive logs
+        if: ${{ always() }}
+        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+        with:
+          name: ${{ inputs.logsartifact }}
+          path: |
+            server/gotestsum.json
+            server/report.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@c0e4b81aaa0067314a2d0d06e19b512c9d8af4f5 # v3.7.7
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: server/report.xml
+          check_name: ${{ inputs.name }} (Results)
+          job_name: ${{ inputs.name }}
